version: "1.0.0"
environment: "development"

# Global scheduling configuration
scheduling:
  default_schedule: "interval"
  default_interval_minutes: 5
  max_concurrent_syncs: 10
  sync_timeout_minutes: 30
  max_retries: 3
  retry_delay_seconds: 30
  rate_limit_backoff_seconds: 60
  max_files_per_sync: 1000
  batch_size: 50

# Logging configuration
log_level: "INFO"
log_format: "json"

# Security and monitoring
require_https: true
webhook_timeout_seconds: 30
health_check_interval_minutes: 5
metrics_enabled: true

# Sync endpoints configuration
endpoints:
  # Google Drive endpoint (commented out for now)
  # - name: "Engineering Documents"
  #   endpoint_type: "google_drive"
  #   project_id: "engineering_docs"
  #   user_id: "engineering@company.com"
  #   description: "Engineering documentation and drawings"
  #   
  #   # Google Drive specific configuration
  #   endpoint_details:
  #     credentials_path: "./credentials/google-service-account.json"
  #     include_shared: true
  #     file_types: ["pdf", "dwg", "docx", "xlsx"]
  #     max_file_size_mb: 100
  #     exclude_patterns: ["*temp*", "*backup*"]
  #   
  #   # Sync schedule
  #   schedule: "interval"
  #   schedule_config:
  #     interval_minutes: 5
  #   
  #   # File filtering
  #   max_files_per_sync: 500
  #   
  #   # Status
  #   is_active: true
  #   tags: ["engineering", "documentation"]

  # Autodesk Construction Cloud endpoint
  - name: "Project 0001"
    endpoint_type: "autodesk_construction_cloud"
    project_id: "project_0001"
    user_id: "admin"
    description: "Autodesk Construction Cloud Project 0001"
    
    # Autodesk specific configuration
    endpoint_details:
      client_id: "${CONNECTOR_AUTODESK_CLIENT_ID}"
      client_secret: "${CONNECTOR_AUTODESK_CLIENT_SECRET}"
      project_id: "b.6c2cffb0-e8c8-43d3-b415-e53f4377cedb"  # Your Autodesk project ID with b. prefix
      include_subfolders: true
      file_types: ["rvt", "dwg", "ifc", "nwd", "pdf"]
      include_versions: true
    
    # Sync schedule
    schedule: "interval"
    schedule_config:
      interval_minutes: 5
    
    # File filtering
    max_files_per_sync: 1000
    
    # Status
    is_active: true
    tags: ["project_0001"]